apiVersion: v1
kind: ConfigMap
metadata:
  name: flight-config
  namespace: flight-dashboard
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_NAME: "skylink"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  ML_SERVICE_URL: "http://ml-service:5002"
  NODE_ENV: "production"
  CORS_ORIGIN: "http://localhost:8080"
